version: '3.8'
services:
  database:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}